version: "3.8"

services:
  web:
    container_name: simple_test
    build: .
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py loaddata initial_data.json &&
             python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8080"
    volumes:
      - ./static/:/static
      - ./media/:/media
      - ./:/app
    restart: always
    depends_on:
      - db
    networks:
      - app_network
    env_file:
      - .env

  db:
    image: postgres:13
    container_name: postgres_service
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data:
  media:
  static: