# Generated by Django 5.0.6 on 2024-06-18 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Полное имя сотрудника. Можно указывать через пробел', max_length=200, verbose_name='Полное имя')),
                ('job_title', models.CharField(help_text='Должность сотрудника', max_length=200, verbose_name='Должность')),
                ('employment_date', models.DateField(help_text='Укажите дату приема на работу', verbose_name='Дата приема на работу')),
                ('salary', models.DecimalField(decimal_places=2, help_text='Укажите размер заработной платы сотрудника', max_digits=10, verbose_name='Зарплата')),
                ('department', models.ForeignKey(help_text='Отдел в котором работает сотрудник', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='departments.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name'],
            },
        ),
    ]
